namespace ECommerceOrderManagement.API.Features.Orders.CreateOrder;

public sealed record CreateOrderRequest(CreateOrderAddressRequest ShippingAddress, CreateOrderAddressRequest BillingAddress, IReadOnlyCollection<CreateOrderItemRequest> Items);