<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ECommerceOrderManagement.Application\ECommerceOrderManagement.Application.csproj" />
    <ProjectReference Include="..\ECommerceOrderManagement.Infrastructure\ECommerceOrderManagement.Infrastructure.csproj" />
    <ProjectReference Include="..\ECommerceOrderManagement.Persistence\ECommerceOrderManagement.Persistence.csproj" />
  </ItemGroup>

</Project>
