<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	  <UserSecretsId>3f22b0ee-5857-40f7-b87f-fa8e63ad059f</UserSecretsId>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
		<PackageReference Include="Microsoft.OpenApi" />
		<PackageReference Include="Swashbuckle.AspNetCore" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>
				runtime; build; native; contentfiles; analyzers; buildtransitive
			</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ECommerceOrderManagement.Application\ECommerceOrderManagement.Application.csproj" />
		<ProjectReference Include="..\ECommerceOrderManagement.Infrastructure\ECommerceOrderManagement.Infrastructure.csproj" />
		<ProjectReference Include="..\ECommerceOrderManagement.Persistence\ECommerceOrderManagement.Persistence.csproj" />
	</ItemGroup>

</Project>
